### ISSUE TITLE
Identifying Errors in $tell recipient's username 

### ISSUE THREAD

**Issue by WenSnake** [Cu3PO42/CuBoid#12]
Is there anyway to identify errors in spelling of a recipient's username, when using $tell?

i.e. The one error where I typed ajkyle instead of ajkyle56 in one of my msgs? 

Maybe look up to see if the typed recipient's nick/username doesn't exist or is unregistered?

**Comment by Cu3PO42** [comment]
Well, f***. I just realized I had plans to allow unregistered usernames because so many people don't register and it was generally pretty requested :/ Suggestions on how to resolve that? Maybe, like a prompt?

**Comment by WenSnake** [comment]
Hmm, if there is a way to identify unregistered usernames, then how about a simple warning: 

Message has been queued for "Username". The recipient's username is unregistered, please check for errors in spelling. 

Else...it's not that big a problem. Go forward with your original plans.

Side Note: How annoying are delivery confirmations for the messages? I know some email services have a feature that tells you if a message has been received and read and/or delivered. I myself can go either way on this being useful or not.

**Comment by Cu3PO42** [comment]
Yeah, probably a confirmation thing would be the best solution. Concerning the delivery confirmations, I guess I could make them opt in? I should probably poll the user base on that one.

**Comment by Cu3PO42** [comment]
I added a query :)
