### ISSUE TITLE
Add generation to $learn.

### ISSUE THREAD

**Issue by Cu3PO42** [Cu3PO42/CuBoid#6]
The $learn command should display the generation in which the move can be learned as, e.g. tutor is ambiguous across generations. But how precisely should this look?
1. Only display information for the latest generation that is available. E.g. if a move can be learned via level up in ORAS and tutor in BW2, only display level up.
2. For each method display the latest generation where it is available.
3. For every method display every generation where it is available.

**Comment by TheSonAlsoRises** [comment]
Option 3 would be preferred, as not everyone would be playing a game from generation 6.

**Comment by Cu3PO42** [comment]
I have so far received mixed feedback between 1 and 3 mostly, but  with the interest to provide as much data as possible, I'm leaning towards option 3, too.

**Comment by Cu3PO42** [comment]
Hmm, if I chose option 3, how would I go about level up moves? Show the level for each and every game? (Or group, like XY/ORAS.)

**Comment by Cu3PO42** [comment]
Apparently there is a bug when a move can be learned at more than one level.
