### ISSUE TITLE
Add $usage for data about current VGC

### ISSUE THREAD

**Issue by Cu3PO42** [Cu3PO42/CuBoid#7]
Integrate with the Pokémon GL API to pull usage data for the current season and display it.

**Comment by Cu3PO42** [comment]
I have the API documented and a SQL query to get the required parameters depending on user input. However I am not sure how I should actually output the data. I'd like some suggestions there, please.

Please keep in mind that the number of lines should be fairly minimal, since IRC can and will kick for flooding.

**Comment by Cu3PO42** [comment]
Specifically, I am talking about the data you get from Pokémon GL about the usage of Pokémon in the current meta. See [here](http://3ds.pokemon-gl.com/battle/oras/#double) to get sample data.

This includes most commonly used moves, items, abilities, the Pokémon that feint to this one and the ones this one faints to.

**Comment by TheSonAlsoRises** [comment]
That is a lot of information to display, especially in text mode.

Maybe use something like `$usage [pokemon] [singles|doubles|etc.] [moves|ability|etc.]`? Or just limit yourself to `$usage [pokemon]` and return to URL to the PGL site.

**Comment by Cu3PO42** [comment]
Specifying the battle type is definitely neccessary. I am currently leaning towards outputting a link and the top 4 items/... or so in table form.

**Comment by Cu3PO42** [comment]
Ended up doing PM.
